### PR TITLE
Update year to 2016

### PR DESCRIPTION
**Pull request by Razer6**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by GrahamCampbell** [comment]
This is incorrect.

**Comment by GrahamCampbell** [comment]
The earliest year MUST be used.

**Comment by jbrooksuk** [comment]
I read somewhere that it doesn't, for sure.

**Comment by jbrooksuk** [comment]
But according to https://www.copyrightservice.co.uk/copyright/p03_copyright_notices you should include the earliest date too.

**Comment by Razer6** [comment]
2015-2016?

**Comment by jbrooksuk** [comment]
2014 :)

You can use `{{ date('Y') }}` to show the latest year in the footer by the way.

**Comment by GrahamCampbell** [comment]
`2015-{{ date('Y') }}` would be most correct

**Comment by jbrooksuk** [comment]
2014

**Pull request merged**
